// <auto-generated />
using System;
using BurgerHouse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BurgerHouse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BurgerHouseDbContext))]
    [Migration("20260906220021_EnforceSingleActivePaymentPerOrder")]
    partial class EnforceSingleActivePaymentPerOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("BurgerHouse.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("BurgerHouse.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observation")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("BurgerHouse.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalPaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPaymentId")
                        .IsUnique();

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (1, 2)");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("BurgerHouse.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "burger-praiano",
                            IsActive = true,
                            Name = "O Praiano",
                            Price = 43.90m
                        },
                        new
                        {
                            Id = 2,
                            Code = "burger-onion-rings",
                            IsActive = true,
                            Name = "O Famoso Onion Ring",
                            Price = 43.90m
                        },
                        new
                        {
                            Id = 3,
                            Code = "burger-crispy-chicken-cheddar",
                            IsActive = true,
                            Name = "Crispy Chicken Cheddar",
                            Price = 35.90m
                        },
                        new
                        {
                            Id = 4,
                            Code = "burger-outback-king",
                            IsActive = true,
                            Name = "O Outback King",
                            Price = 43.90m
                        },
                        new
                        {
                            Id = 5,
                            Code = "burger-chicken-grill-supreme",
                            IsActive = true,
                            Name = "Chicken Grill Supreme",
                            Price = 35.90m
                        },
                        new
                        {
                            Id = 6,
                            Code = "burger-joia-da-coroa",
                            IsActive = true,
                            Name = "A Joia da Coroa",
                            Price = 58.90m
                        },
                        new
                        {
                            Id = 7,
                            Code = "side-fritas-cheddar",
                            IsActive = true,
                            Name = "Fritas Cheddar & Bacon",
                            Price = 24.90m
                        },
                        new
                        {
                            Id = 8,
                            Code = "side-batata-rustica",
                            IsActive = true,
                            Name = "Batatas Rústicas da Casa",
                            Price = 18.90m
                        },
                        new
                        {
                            Id = 9,
                            Code = "side-aneis-cebola",
                            IsActive = true,
                            Name = "Anéis de Cebola Crocantes",
                            Price = 22.90m
                        },
                        new
                        {
                            Id = 10,
                            Code = "drink-coca-lata",
                            IsActive = true,
                            Name = "Coca-Cola Lata",
                            Price = 5.90m
                        },
                        new
                        {
                            Id = 11,
                            Code = "drink-guarana-antarctica",
                            IsActive = true,
                            Name = "Guaraná Antarctica",
                            Price = 5.90m
                        });
                });

            modelBuilder.Entity("BurgerHouse.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("BurgerHouse.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerHouse.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BurgerHouse.Domain.Entities.Payment", b =>
                {
                    b.HasOne("BurgerHouse.Domain.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BurgerHouse.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
